FROM 368539636127.dkr.ecr.us-east-2.amazonaws.com/roquendo/php8:latest
EXPOSE 80 443

RUN apk add nginx

COPY images/configs/nginx/laravel-fpm.conf /etc/nginx/http.d/default.conf

COPY images/scripts/php-nginx.sh /scripts/entrypoint.sh

RUN chmod 777 /scripts/entrypoint.sh
RUN mkdir -p \
    /var/log/nginx
RUN touch \
    /var/log/nginx/access.log \
    /var/log/nginx/error.log

