FROM 368539636127.dkr.ecr.us-east-2.amazonaws.com/roquendo/php8:latest

LABEL org.afluenta.php.authors="rodolfoquendo@gmail.com"
LABEL org.afluenta.php.version="8.2"
LABEL org.afluenta.php.os="alpine"
LABEL org.afluenta.php.nginx="0"
LABEL org.afluenta.php.cron="0"
LABEL org.afluenta.php.xdebug="1"

RUN pecl install xdebug
COPY images/configs/php/php.test.ini /usr/local/etc/php/php.ini

RUN adduser -D gitlab-runner
RUN chgrp gitlab-runner /afluenta-platform 
RUN chmod g+rwx /afluenta-platform 